### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by Peckchamp14** [Kylart/Anikki#2]
i have installed all the needed dependencies and then ran:

git clone --recursive https://github.com/Kylart/Anikki 
cd Anikki
cp .env.example .env
flutter build linux

but then i got these errors:
CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/CMakeLists.txt:17 (add_library):
  Target "media_kit_video_plugin" links to target "PkgConfig::mpv" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_native_event_loop/src/CMakeLists.txt:52 (add_library):
  Target "media_kit_native_event_loop" links to target "PkgConfig::mpv" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/CMakeLists.txt:17 (add_library):
  Target "media_kit_video_plugin" links to target "PkgConfig::mpv" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_native_event_loop/src/CMakeLists.txt:52 (add_library):
  Target "media_kit_native_event_loop" links to target "PkgConfig::mpv" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?

CMake Generate step failed.  Build files cannot be regenerated correctly.
Building Linux application...                                           
Unable to generate build files

**Comment by Kylart** [comment]
Oh it seems I forgot some instructions for Linux

Using your package manager, simply install libmpv. For example on ubuntu:
```shell
sudo apt-get install -y ninja-build libgtk-3-dev mpv libmpv-dev
```

Then try again and you should be good to go.

**Comment by Peckchamp14** [comment]
sorry for the late reply but it still doesnt work, after following your steps it gives out these errors:

CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_video/linux/CMakeLists.txt:17 (add_library):
  Target "media_kit_video_plugin" links to target "PkgConfig::mpv" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_native_event_loop/src/CMakeLists.txt:52 (add_library):
  Target "media_kit_native_event_loop" links to target "PkgConfig::mpv" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?


it says that mpv was not found but it is installed:

❯ sudo dnf list installed "*mpv*"
Installed Packages
mpv.x86_64                                              0.35.1-4.fc38                                         @fedora
mpv-devel.x86_64                                        0.35.1-4.fc38                                         @fedora
mpv-libs.x86_64                                         0.35.1-4.fc38                                         @fedora

**Comment by Kylart** [comment]
I would guess on a cache problem, please run
```bash
flutter clean && rm -rf linux/flutter/ephemeral/.plugin_symlinks
```

If it still does not work after that, you would have better chances of having good help on the `media_kit` library repository since this is coming from them. You can find them [here](https://github.com/media-kit/media-kit)
