### ISSUE TITLE
Issues with building on windows

### ISSUE THREAD

**Issue by TubaApollo** [Kylart/Anikki#3]
**Describe the bug**
It may not be a bug, but i am not able to build the application on Windows 

**To Reproduce**
1. Build the application like described in the readme
2. See error: `CMake Error at flutter/ephemeral/.plugin_symlinks/media_kit_libs_windows_video/windows/CMakeLists.txt:74 (message):
  mpv-dev-x86_64-20230408-git-7ae7fc0.7z integrity check failed.`

**Expected behavior**
Build successful 

**Screenshots**
![grafik](https://github.com/Kylart/Anikki/assets/86665265/12e15139-318b-496b-8ded-3c41513331b2)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser -
 - Version newest version in master, i guess?

**Additional context**
I am using flutter version: 3.12.0 

Thank you!! :)

**Comment by Kylart** [comment]
Can you try running the following command in a terminal:
```powershell
flutter clean; git checkout new-design; flutter run
```

My guess would be that there is a versioning problem since I haven't updated the `media_kit` versions on the `dev` branch since I'm currently working on the `new-design` branch (soon to be merged).

**Comment by TubaApollo** [comment]
I'll try that, thanks!

**Comment by TubaApollo** [comment]
Works, i'll close this
