### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by nyouness** [Kylart/Anikki#4]
Hii, your project got my attention and i want to try it but i dont know anything , i installed GIT and Flutter idk what to do now if  please help and make simple step by step how to install for noobs like me im on windows 10 and thanks a loot in advance!

**Comment by Kylart** [comment]
Hello,

I'm currently working on automating a `setup.exe` that would install the app. In the meantime, all you have to do is the following:
1. Install Flutter (you did it)
2. Download the source code (zip or via git, e.g. `git clone --depth=1 https://github.com/Kylart/anikki`)
3. Open a terminal in the folder
4. Run `flutter build windows --release`
5. Run `start build\windows\runner\Release`
6. Open `anikki.exe`

Hope that helps

**Comment by Kylart** [comment]
You can now also download it as an artifact of any action. For example, [here](https://github.com/Kylart/Anikki/actions/runs/6449539295) or at [this link](https://github.com/Kylart/Anikki/suites/17008463273/artifacts/971399927)

**Comment by nyouness** [comment]
i cant download in full connection speed something with github .... if  please upload it to some free site like https://pixeldrain.com/

**Comment by nyouness** [comment]
i manged to download it with 40kb , i installed it but nothing showing only white 
![Screenshot 2023-10-09 111657](https://github.com/Kylart/Anikki/assets/117232906/2fb0671e-581e-4008-a9d6-eee08d8ce1c1)

**Comment by Kylart** [comment]
Yea I discovered that as well, it seems to be a write access problem that I'm yet to fix. In the meantime, you'll need to build it yourself.

If you want to generate a `setup.exe` yourself, you can run this in a Windows terminal:

```powershell
cd path/to/anikki
dart pub global activate flutter_distributor
flutter_distributor package --platform windows --targets exe
start dist/1.0.0
```

OR, simply
```powershell
cd path/to/anikki
flutter build windows --release
start build/runner/Release
```
and use the `anikki.exe` file.

**Comment by Kylart** [comment]
> Yea I discovered that as well, it seems to be a write access problem that I'm yet to fix. In the meantime, you'll need to build it yourself.
> 
> If you want to generate a `setup.exe` yourself, you can run this in a Windows terminal:
> 
> ```powershell
> cd path/to/anikki
> dart pub global activate flutter_distributor
> flutter_distributor package --platform windows --targets exe
> start dist/1.0.0
> ```
> 
> OR, simply
> 
> ```powershell
> cd path/to/anikki
> flutter build windows --release
> start build\windows\runner\Release
> ```
> 
> and use the `anikki.exe` file.

After some tweaking, this problem should be fixed and you should be able to download any exe from GitHub actions 🙏
